name: ci

on:
  push:
    branches: [next]
  pull_request:
    branches: [next]

jobs:
  check-lockfile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Run actions/setup-node@v3 (${{ matrix.node-version}})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn
        run: yarn
      - name: Check yarn.lock for changes
        run: git diff --quiet -- yarn.lock

  format-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Run actions/setup-node@v3 (${{ matrix.node-version}})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn
        run: yarn --frozen-lockfile
      - name: yarn format:check
        run: yarn format:check

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Run actions/setup-node@v3 (${{ matrix.node-version}})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn
        run: yarn --frozen-lockfile
      - name: yarn lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Run actions/setup-node@v3 (${{ matrix.node-version}})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn
        run: yarn --frozen-lockfile
      - name: yarn build
        run: yarn build

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Run actions/setup-node@v3 (${{ matrix.node-version}})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn
        run: yarn --frozen-lockfile
      - name: yarn build
        run: yarn build # Prime cache.
      - name: yarn test
        run: yarn test
