name: ci

on:
  push:
    branches: [next]
  pull_request:
    branches: [next]

jobs:
  check-lockfile-and-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Run actions/setup-node@v3 (${{ matrix.node-version}})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn
        run: yarn --immutable --immutable-cache --check-cache

  format-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Run actions/setup-node@v3 (${{ matrix.node-version}})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn
        run: yarn --immutable --immutable-cache
      - name: yarn format:check
        run: yarn format:check

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Run actions/setup-node@v3 (${{ matrix.node-version}})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn
        run: yarn --immutable --immutable-cache
      - name: yarn lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Run actions/setup-node@v3 (${{ matrix.node-version}})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn
        run: yarn --immutable --immutable-cache
      - name: yarn build
        run: yarn build

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Run actions/setup-node@v3 (${{ matrix.node-version}})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn
        run: yarn --immutable --immutable-cache
      - name: yarn build
        run: yarn build # Prime cache.
      - name: yarn test
        run: yarn test
